import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { Poppins } from 'next/font/google';
import NavBar from "@/components/customs/navbar";
import { appConstants } from "@/lib/constants";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={cn("font-sans", inter.variable)}
     >
      <body
        className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} antialiased`} 
      >
        <main className="font-sans">
          <NavBar 
          className="" 
          navlist={appConstants.navlist}/>
          <>
            {children}
          </>
        </main>
      </body>
    </html>
  );
}
